Intelliface/Controllers/LocationController.cs
using Intelliface.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Net.Http;
using System.Text;
using System.Text.Json;

namespace Intelliface.Controllers
{
    public class LocationController : Controller
    {
        private readonly HttpClient _httpClient;
        private readonly ILogger<LocationController> _Ilogger;

        public LocationController(ILogger<LocationController> logger, IHttpClientFactory httpClientFactory)
        {
            _Ilogger = logger;
            _httpClient = httpClientFactory.CreateClient("IntellifaceClient");
        }
        public async Task<IActionResult> Records()
        {

            var respone = await _httpClient.GetAsync("/api/Location/GetAll");
            var json = await respone.Content.ReadAsStringAsync();

            var locations = JsonSerializer.Deserialize<List<ReadVM<LocationVM>>>(json);

            return View(locations);
        }

        public async Task<IActionResult> Create() => View();



        [HttpPost]
        public async Task<IActionResult> Create(LocationVM location)
        {
            if (!ModelState.IsValid)
            {
                return Redirect("Create");
            }
            var json = JsonSerializer.Serialize(location);
            var content = new StringContent(json, Encoding.UTF8, "application/json");
            var response = await _httpClient.PostAsync("/api/Location/Create", content);
            response.EnsureSuccessStatusCode();

            return RedirectToAction("Records");
        }

        public async Task<IActionResult> Update(int id)
        {
            var response = await _httpClient.GetAsync($"/api/Location/GetById/{id}");
            response.EnsureSuccessStatusCode();
            var json = await response.Content.ReadAsStringAsync();
            var location = JsonSerializer.Deserialize<ReadVM<LocationVM>>(json);
            return View(location);
        }
        [HttpPut]
        public async Task<IActionResult> Update(int id, [FromBody] LocationVM location)
        {
            if (!ModelState.IsValid)
            {
                return Redirect("Update");
            }
            var json = JsonSerializer.Serialize(location);
            var content = new StringContent(json, Encoding.UTF8, "application/json");
            var response = await _httpClient.PutAsync($"/api/Location/Update/{id}", content);
            response.EnsureSuccessStatusCode();

            return RedirectToAction("Records");
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(string id)
        {
            var response = await _httpClient.DeleteAsync($"/api/Location/Delete/{id}");
            response.EnsureSuccessStatusCode();
            return RedirectToAction("Records");
        }
    }
}

Intelliface/Views/Location/Create.cshtml
<link rel="stylesheet" href="~/css/create.css" />
<main class="main">
    <div class="topbar">
        <input type="text" placeholder="Searchbox"
               style="padding: 8px 12px; width: 300px; border: 1px solid #ccc; border-radius: 5px;">
        <div>
            <img src="images/man-user-circle-icon copy.svg" alt="User"
                 style="width: 50px; height: 50px; border-radius: 50%; vertical-align: middle;">
        </div>
    </div>

    <div class="title">Locations</div>
    <div class="breadcrumb">Manage / Location / <strong>Add Location</strong></div>

    <div class="form-container">
        <h3> Add an Department </h3>

        <form asp-action="Create" asp-controller="Location" method="post">
            <div class="row">
                <input type="text" placeholder="Name" name="address" style="background-color:#2b2b3d00;">
            </div>
            <div class="row">
                <input type="number" step="any" placeholder="Latitude" name="latitude" style="background-color:#2b2b3d00;" />
                <input type="number" step="any" placeholder="Longitude" name="longitude" style="background-color:#2b2b3d00;" />
            </div>
            <div class="buttons">
                <button type="submit" class="submit-btn">Submit</button>
                <button type="reset" class="reset-btn">Reset</button>
            </div>
        </form>
    </div>
</main>

Intelliface/Views/Location/Records.cshtml
  @model List<ReadVM<LocationVM>>
    <link rel="stylesheet" href="~/css/location.css" />
    <main class="main">
        <div class="topbar">
            <input type="text" placeholder="Search" style="padding: 8px 12px; border-radius: 6px; border: 1px solid #ccc; width: 250px;">
            <div><img src="images/man-user-circle-icon copy.svg" alt="User"></div>
        </div>
        <div class="title">Location</div>
        <div class="breadcrumb">Manage / <strong>Location</strong></div>
        <div class="location-form">
            <button onclick="addLocation()">Add Location</button>
        </div>
        <div class="table-box">
            <table>
                <thead>
                    <tr>
                        <th>Location Name</th>
                        <th>Latitude</th>
                        <th>Longitude</th>
                        <th>Manage</th>
                    </tr>
                </thead>
            <tbody id="locationTable">
            @{
                for (int i = 0; i < @Model.Count; i++)
                {
                    <tr>
                        <td>@Model[i].data.address</td>
                        <td>@Model[i].data.latitude</td>
                        <td>@Model[i].data.longitude</td>
                        <td class="actions">
                                <a asp-action="Update" asp-controller="Location" asp-route-id="@Model[i].id">
                            <img src="images/edit-05-svgrepo-com.svg" alt="Edit" width="18" onclick="toggleEdit(this)">
                            </a>
                                <a href="#" onclick="confirmDelete(@Model[i].id)">
                            <img src="images/trash.png" alt="Delete" width="18" class="delete-icon">
                            </a>
                        </td>
                    </tr>
                }
            }
               </tbody>
            </table>
        <script>
                           function confirmDelete(id) {
                if (confirm("Are you sure to delete this Location?")) {
                    fetch(`/Location/Delete/${id}`, {
                        method: 'DELETE'
                    })
                    .then(response => {
                        if (response.ok) {

                            window.location.reload();
                        } else {
                            alert("Delete failed.");
                        }
                    })
                    .catch(error => {
                        alert("Error: " + error);
                    });
                }
            }
        </script>
        </div>
    </main>

  

Intelliface/Views/Location/Update.cshtml
@model ReadVM<LocationVM>

<link rel="stylesheet" href="~/css/create.css" />
<main class="main">
    <div class="topbar">
        <input type="text" placeholder="Searchbox"
               style="padding: 8px 12px; width: 300px; border: 1px solid #ccc; border-radius: 5px;">
        <div>
            <img src="images/man-user-circle-icon copy.svg" alt="User"
                 style="width: 50px; height: 50px; border-radius: 50%; vertical-align: middle;">
        </div>
    </div>

    <div class="title">Locations</div>
    <div class="breadcrumb">Manage / Location / <strong>Add Location</strong></div>

    <div class="form-container">
        <h3> Add an Department </h3>

        <form id="updateForm">

            <input type="hidden" name="id" value="@Model.id"/>

            <div class="row">
                <input type="text" placeholder="Name" name="address" value ="@Model?.data.address"style="background-color:#2b2b3d00;">
            </div>
            <div class="row">
                <input type="number" step="any" placeholder="Latitude" name="latitude" value="@Model?.data.latitude"style="background-color:#2b2b3d00;" />
                <input type="number" step="any" placeholder="Longitude" name="longitude" value="@Model?.data.longitude" style="background-color:#2b2b3d00;" />
            </div>
            <div class="buttons">
                <button type="submit" class="submit-btn">Submit</button>
                <button type="reset" class="reset-btn">Reset</button>
            </div>
        </form>
         <script>
            $('#updateForm').submit(function (e) {
                e.preventDefault();

                var id = $('input[name="id"]').val();
                var address = $('input[name=address]').val();
                var latitude = $('input[name="latitude"]').val();
                var longitude = $('input[name="longitude"]').val();
                

                var data = {
                   id: id,
                    address: address,
                    latitude: latitude,
                    longitude: longitude
                };


                $.ajax({
                    url: '/Location/Update/' + id,
                    type: 'PUT',
                    contentType: 'application/json',
                    data: JSON.stringify(data),
                    success: function (response) {
                        alert('Succesfull!');

                        window.location.href = '/Location/Records';
                    },
                    error: function (xhr) {
                        alert('Something went wrong: ' + xhr.responseText);
                    }
                });
            });
        </script>
    </div>
</main>